import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "./_components/Navbar";
import SessionProvider from "@/app/(meds)/doctor/_components/SessionProvider";

import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Appointments - COdecure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />

          <main className="flex-grow">
            {children}
            <Footer />
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
